service: devquest-job-scraper
provider:
  name: aws
  runtime: python3.8
  region: us-east-1

plugins:
  - serverless-wsgi
  - serverless-python-requirements

custom:
  wsgi:
    app: main.app 
    packRequirements: false

functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

package:
  exclude:
    - node_modules/**
    - venv/**
    - .gitignore
    - .git/**

custom:
  pythonRequirements:
    dockerizePip: true
    useStaticCache: true
    useDownloadCache: true