service: dq-webscrape
provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  environment:
    BUCKET: dq-webscrape-dev-serverlessdeploymentbucket-kjzi490naosv
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "arn:aws:s3:::${self:provider.environment.BUCKET}/*"

plugins:
  - serverless-wsgi
  - serverless-python-requirements


custom:
  wsgi:
    app: main.app
    packRequirements: false

  pythonRequirements:
    dockerizePip: true
    useStaticCache: true
    useDownloadCache: true
    slim: true
    strip: true

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: '{proxy+}'
          method: ANY
          cors: true
          
package:
  exclude:
    - node_modules/**
    - venv/**
    - .gitignore
    - .git/**
    - Pipfile
    - Pipfile.lock
    - handler.py