service: devquest-job-scraper
provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  deploymentBucket:
    name: job-scraper-serverless-layers-bucket

plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-layers


custom:
  wsgi:
    app: main.app
    packRequirements: false

  pythonRequirements:
    dockerizePip: true
    useStaticCache: true
    useDownloadCache: true
    layer: true

layers:
  common:
    path: layer

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: '{proxy+}'
          method: ANY
          cors: true
    layers:
      - {Ref: CommonLambdaLayer}

package:
  exclude:
    - node_modules/**
    - venv/**
    - .gitignore
    - .git/**
    - Pipfile
    - Pipfile.lock
    - handler.py