service: devquest-job-scraper
provider:
  name: aws
  runtime: python3.11
  region: us-east-1

plugins:
  - serverless-wsgi
  - serverless-python-requirements

custom:
  wsgi:
    app: main.app
    packRequirements: false

  pythonRequirements:
    dockerizePip: true
    useStaticCache: true
    useDownloadCache: true

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: '{proxy+}'
          method: ANY
          cors: true

package:
  exclude:
    - node_modules/**
    - venv/**
    - .gitignore
    - .git/**
    - Pipfile
    - Pipfile.lock
    - handler.py